### ISSUE TITLE
Include std headers for runtime_error

### ISSUE THREAD

**Issue by chrhck** [icecube/LeptonInjector#13]
On modern GCC (12.3.0) LeptonInjector fails to compile, because `runtime_error` needs the `<stdexcept>` header.

**Comment by chrhck** [comment]
`diff --git a/public/LeptonInjector/Particle.h b/public/LeptonInjector/Particle.h
index 0a84166..8dd6e1a 100644
--- a/public/LeptonInjector/Particle.h
+++ b/public/LeptonInjector/Particle.h
@@ -9,6 +9,7 @@
 
 #include <string>
 #include <exception>
+#include <stdexcept>
 #include <utility> // std::pair
 
 #include <LeptonInjector/Constants.h>
`

**Comment by cnweaver** [comment]
This should be resolved by https://github.com/icecube/LeptonInjector/commit/e0969435c6da616bea22af9451270da1c3647659 , but as I don't have a system with GCC 12 handy to make certain, please reopen if it turns out not to be.

**Comment by chrhck** [comment]
thanks, fixed
